sudo : required
services: 
   - docker


before_install:
   - docker build -t tatocar/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run tatocar/react-test npm test -- --coverage

after_success:
   - docker build -t tatocar/multi-client ./client
   - docker build -t tatocar/multi-nginx ./nginx
   - docker build -t tatocar/multi-server ./server
   - docker build -t tatocar/multi-worker ./worker
   # Log in to the docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   # Take those images and push them to docker hub
   - docker push tatocar/multi-client
   - docker push tatocar/multi-nginx
   - docker push tatocar/multi-server
   - docker push tatocar/multi-worker

deploy:
   provider: elasticbeanstalk
   region: "us-west-2"
   app: "multi-docker"
   env: "MultiDocker-env"
   bucket_name: "elasticbeanstalk-us-west-2-121061333352"
   bucket_path: "multi-docker"
   on:
      branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
      secure: "$AWS_SECRET_KEY"
